<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.0">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.10" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Npgsql" Version="9.0.4" />
        <PackageReference Include="xunit" Version="2.4.1" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\IV.DX.Application.Contracts\IV.DX.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\..\IV.DX.Application\IV.DX.Application.csproj" />
        <ProjectReference Include="..\..\..\IV.DX.Domain\IV.DX.Domain.csproj" />
        <ProjectReference Include="..\..\..\IV.DX.Hosting\IV.DX.Hosting.csproj" />
        <ProjectReference Include="..\..\..\IV.DX.Kernel\IV.DX.Kernel.csproj" />
        <ProjectReference Include="..\..\..\IV.DX.Persistence.Contracts\IV.DX.Persistence.Contracts.csproj" />
        <ProjectReference Include="..\..\..\IV.DX.Persistence\IV.DX.Persistence.csproj" />
        <ProjectReference Include="..\IV.DX.Shared.UnitTests\IV.DX.Shared.UnitTests.csproj" />
    </ItemGroup>

</Project>
