<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <PackageId>IV.DX</PackageId>
        <Authors>Ignis Vitalis</Authors>
        <Company>IgnisVitalis</Company>
        <Description>Data provider service.</Description>
        <RepositoryUrl>https://github.com/IgnisVitalis/IV.DX</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>utilities;</PackageTags>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="MigrationScripts\**" />
      <EmbeddedResource Remove="MigrationScripts\**" />
      <None Remove="MigrationScripts\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="InitScripts\Core\01_01_0000_Core_DXEnumDefinitionUnit.dat" />
      <None Remove="InitScripts\Core\01_01_0001_Core_DXElementDefinitionUnit.dat" />
      <None Remove="InitScripts\Core\01_01_0002_Core_DXUnitDefinitionUnit.dat" />
      <None Remove="InitScripts\Core\01_01_0003_Core_DXRelationDefinitionUnit.dat" />
      <None Remove="InitScripts\Core\01_01_0004_Core_DXInheritanceInitCore.dat" />
      <None Remove="InitScripts\Core\01_01_0005_Core_DXEnumDefinitionUnit.dat" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="InitScripts\CorePostInit.json">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
            <PackageCopyToOutput>true</PackageCopyToOutput>
            <Pack>true</Pack>
        </EmbeddedResource>
        <EmbeddedResource Include="InitScripts\CorePreInit.json">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
            <PackageCopyToOutput>true</PackageCopyToOutput>
            <Pack>true</Pack>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="InitScripts\Core\01_01_0000_Core_DXEnumDefinitionUnit.dat">
      </EmbeddedResource>
      <EmbeddedResource Include="InitScripts\Core\01_01_0001_Core_DXElementDefinitionUnit.dat">
      </EmbeddedResource>
      <EmbeddedResource Include="InitScripts\Core\01_01_0002_Core_DXUnitDefinitionUnit.dat">
      </EmbeddedResource>
      <EmbeddedResource Include="InitScripts\Core\01_01_0003_Core_DXRelationDefinitionUnit.dat">
      </EmbeddedResource>
      <EmbeddedResource Include="InitScripts\Core\01_01_0004_Core_DXInheritanceInitCore.dat">
      </EmbeddedResource>
      <EmbeddedResource Include="InitScripts\Core\01_01_0005_Core_DXEnumDefinitionUnit.dat">
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.10" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Npgsql" Version="9.0.4" />
        <PackageReference Include="Tenekon.MSBuild.Packaging.ProjectBuildInPackage" Version="2.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\IV.DX.Application.Contracts\IV.DX.Application.Contracts.csproj" PrivateAssets="all" />
        <ProjectReference Include="..\IV.DX.Application\IV.DX.Application.csproj" PrivateAssets="all" />
        <ProjectReference Include="..\IV.DX.Domain\IV.DX.Domain.csproj" PrivateAssets="all" />
        <ProjectReference Include="..\IV.DX.Kernel\IV.DX.Kernel.csproj" PrivateAssets="all" />
        <ProjectReference Include="..\IV.DX.Persistence.Contracts\IV.DX.Persistence.Contracts.csproj" PrivateAssets="all" />
        <ProjectReference Include="..\IV.DX.Persistence\IV.DX.Persistence.csproj" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\..\README.md" Pack="true" PackagePath="" />
    </ItemGroup>
</Project>
