<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <IsTestProject>false</IsTestProject>
        <ExcludeFromCodeCoverage>true</ExcludeFromCodeCoverage>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.10" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Npgsql" Version="9.0.4" />
        <PackageReference Include="xunit.abstractions" Version="2.0.3" />
        <PackageReference Include="xunit.extensibility.core" Version="2.4.1" />
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="8.0.0" />
        <PackageReference Include="Testcontainers.PostgreSql" Version="4.12.0" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\..\IV.DX.Application.Contracts\IV.DX.Application.Contracts.csproj" />
      <ProjectReference Include="..\..\..\IV.DX.Application\IV.DX.Application.csproj" />
      <ProjectReference Include="..\..\..\IV.DX.Domain\IV.DX.Domain.csproj" />
      <ProjectReference Include="..\..\..\IV.DX.Hosting\IV.DX.Hosting.csproj" />
      <ProjectReference Include="..\..\..\IV.DX.Kernel\IV.DX.Kernel.csproj" />
      <ProjectReference Include="..\..\..\IV.DX.Persistence.Contracts\IV.DX.Persistence.Contracts.csproj" />
      <ProjectReference Include="..\..\..\IV.DX.Persistence\IV.DX.Persistence.csproj" />
    </ItemGroup>
    <ItemGroup>
        <None Update="MigrationScripts\Test.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\**\*.dx">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>

        <None Update="MigrationScripts\Sync.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Sync\**\*.dx">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
