<Project Sdk="Microsoft.NET.Sdk">


    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="3.1.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="xunit.abstractions" Version="2.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\IV.DX.Hosting\IV.DX.Hosting.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="IV.DataProvider.Persistence.config.mysql">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0000_Test_TPassportGenBlock.dd">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0001_Test_TPositionGenBlock.dd">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0002_Test_TUserGenBlock.dd">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0003_Test_TDeviceGenBlock.dd">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0004_Test_TBookGenBlock.dd">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0005_Test_TBookChapterBlock.dd">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0006_Test_TDocumentGenBlock.dd">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0007_Test_TPassportObject.dd">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0008_Test_TPositionObject.dd">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0009_Test_TUserObject.dd">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0010_Test_TDeviceObject.dd">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0011_Test_TBookObject.dd">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0012_Test_TDocumentObject.dd">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0019_Test_TUserObject.rd">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0020_Test_TUserObject.dat">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0021_Test_TPassportObject.dat">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0022_Test_TPositionObject.dat">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0023_Test_TDeviceObject.dat">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0024_Test_TBookObject.dat">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0025_Test_TDocumentObject.dat">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="MigrationScripts\Test\01_01_0026_Test_DXRelationItemUnit.dat">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
