<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Data\Add\01_01_0000_DX_DXQueryColumnElement.dat" />
      <None Remove="Data\Add\01_01_0001_DX_DXQueryMainElement.dat" />
      <None Remove="Data\Add\01_01_0002_DX_DXQueryUnit.dat" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Data\Add\01_01_0000_DX_DXQueryColumnElement.dat" />
      <EmbeddedResource Include="Data\Add\01_01_0001_DX_DXQueryMainElement.dat" />
      <EmbeddedResource Include="Data\Add\01_01_0003_DX_DXFilterUnit.dat" />
      <EmbeddedResource Include="Data\Add\01_01_0002_DX_DXQueryUnit.dat" />
      <EmbeddedResource Include="Data\Add.json" />
      <EmbeddedResource Include="Data\Core\01_01_0000_Core_DXEnumDefinitionUnit.dat" />
      <EmbeddedResource Include="Data\Core\01_01_0001_Core_DXElementDefinitionUnit.dat" />
      <EmbeddedResource Include="Data\Core\01_01_0002_Core_DXUnitDefinitionUnit.dat" />
      <EmbeddedResource Include="Data\Core\01_01_0003_Core_DXRelationDefinitionUnit.dat" />
      <EmbeddedResource Include="Data\Core\01_01_0004_Core_DXInheritanceInitCore.dat" />
      <EmbeddedResource Include="Data\Core\01_01_0005_Core_DXEnumDefinitionUnit.dat" />
      <EmbeddedResource Include="Data\CorePostInit.json" />
      <EmbeddedResource Include="Data\CorePreInit.json" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

</Project>
