<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Include="Data\DXSecurity.json" />
      <EmbeddedResource Include="Data\DXQuery.json" />
      <EmbeddedResource Include="Data\DXCorePostInit.json" />
      <EmbeddedResource Include="Data\DXCorePreInit.json" />
      
      <EmbeddedResource Include="Data\DXSecurity\01_01_0000_DXSecurity_DXEnumDefinitionUnit.dx" />
      <EmbeddedResource Include="Data\DXSecurity\01_01_0001_DXSecurity_DXIdentityProviderTypeEnum.dx" />
      <EmbeddedResource Include="Data\DXSecurity\01_01_0002_DXSecurity_DXUnitDefinitionUnit.dx" />
      <EmbeddedResource Include="Data\DXSecurity\01_01_0003_DXSecurity_DXEnumDefinitionUnit.dx" />
      <EmbeddedResource Include="Data\DXSecurity\01_01_0004_DXSecurity_DXGrantEffectEnum.dx" />
      <EmbeddedResource Include="Data\DXSecurity\01_01_0005_DXSecurity_DXUnitGrantElement.dx" />     
      <EmbeddedResource Include="Data\DXQuery\01_01_0000_DXQuery_DXQueryColumnElement.dx" />
      <EmbeddedResource Include="Data\DXQuery\01_01_0002_DXQuery_DXFilterUnit.dx" />
      <EmbeddedResource Include="Data\DXQuery\01_01_0001_DXQuery_DXQueryUnit.dx" />
      <EmbeddedResource Include="Data\DXCore\01_01_0000_DXCore_DXEnumDefinitionUnit.dx" />
      <EmbeddedResource Include="Data\DXCore\01_01_0001_DXCore_DXElementDefinitionUnit.dx" />
      <EmbeddedResource Include="Data\DXCore\01_01_0002_DXCore_DXUnitDefinitionUnit.dx" />
      <EmbeddedResource Include="Data\DXCore\01_01_0003_DXCore_DXRelationDefinitionUnit.dx" />
      <EmbeddedResource Include="Data\DXCore\01_01_0004_DXCore_DXInheritanceInitCore.dx" />
      <EmbeddedResource Include="Data\DXCore\01_01_0005_DXCore_DXEnumDefinitionUnit.dx" />
      <EmbeddedResource Include="Data\DXCore\01_01_0006_DXCore_DXElementToUnitElement.dx" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

</Project>
